.github/workflows/testing.yml, tox.ini
1. Added github action configurations files
2. Fix tox.ini file to use tox in GitHub Actions
We will replace TravisCI with GitHub Actions at some point.
=> Add GitHub Actions

procrustes/generalized.py, procrustes/generic.py, procrustes/orthogonal.py, procrustes/permutation.py, procrustes/rotational.py, procrustes/softassign.py, procrustes/symmetric.py, procrustes/test/test_generic.py, procrustes/test/test_orthogonal.py, procrustes/test/test_permutation.py, procrustes/test/test_softassign.py, procrustes/test/test_symmetric.py
Fix the corresponding tests as well.
=> Fix the return of various Procrustes methods

procrustes/rotational.py
This fixes the rotational matrix which is not right in the previous version.
=> Fix return of rotational Procrustes

procrustes/permutation.py
This fixes the problem of confusing docstrings, trying to solve #23.
=> Update dosstrings for two-sided permutation

HEADER, procrustes/__init__.py, procrustes/generalized.py, procrustes/generic.py, procrustes/kopt.py, procrustes/orthogonal.py, procrustes/permutation.py, procrustes/rotational.py, procrustes/softassign.py, procrustes/symmetric.py, procrustes/test/__init__.py, procrustes/test/test_generalized.py, procrustes/test/test_generic.py, procrustes/test/test_kopt.py, procrustes/test/test_orthogonal.py, procrustes/test/test_permutation.py, procrustes/test/test_rotational.py, procrustes/test/test_softassign.py, procrustes/test/test_symmetric.py, procrustes/test/test_utils.py, procrustes/utils.py, setup.py, updateheaders.py
The HEADER in all files is updated to mention `QC-Devs` community.
=> Update HEADER to mention QC-Devs

procrustes/softassign.py, procrustes/test/test_softassign.py
=> Add k-opt local search heuristic for softassign

setup.py
=> Rename package name: procrustes -> qc-procrustes

docs/conf.py, docs/index.rst, docs/intro_about.rst, docs/intro_citing.rst, docs/intro_contact.rst, docs/intro_license.rst, docs/usr_doc_atom_mapping.rst, docs/usr_doc_chiral_check.rst, docs/usr_doc_installization.rst, docs/usr_doc_protein_align.rst, docs/usr_doc_quick_start.rst, docs/usr_doc_ranking.rst, docs/usr_doc_tutorials.rst, docs/usr_doc_zref.rst, updateheaders.py
This PR mainly deals with updating file headers in `docs` folder and update the installation guide accordingly.
I will clean the files in the `docs` folder a little bit more, but to avoid being a giant PR. This should be ready for review.
=> Update header and refactor installation guide

procrustes/test/test_generic.py, requirements.txt
Update Generic Procrustes tests.
=> Use random matrices for genric Procrustes tests

docs/examples/chirality_check/check_chirality.py, docs/examples/protein_alignment/protein_align.py, procrustes/__init__.py, procrustes/generalized.py, procrustes/orthogonal.py, procrustes/rotational.py, procrustes/test/test_orthogonal.py, procrustes/test/test_rotational.py, setup.py
Some miscellaneous changes and update rotational & 1-sided orthogonal documentation to better explain arguments and show the mathematical formulation.
=> Update rotational & 1-sided orthogonal

procrustes/orthogonal.py, procrustes/test/test_orthogonal.py
1) Change U to Q
2) Fix orthogonal_2sided documentation
3) Fix orthogonal_2sided arguments
=> Update orthogonal documentation & arguments

README.md
Use `conda activate myenv` instead of `source activate myenv` as the `conda` syntax has been updated. Add command line to install dependencies as well.
=> Update README.md with activating virtual env

docs/notebooks/Quick_Start.ipynb
This notebook reproduces the code snippets shown in the manuscript.
=> Add notebook for quick start

procrustes/orthogonal.py, procrustes/permutation.py, procrustes/test/test_orthogonal.py, procrustes/test/test_permutation.py
I built upon @Ali-Tehrani's refactoring of `permutation_2sided` in this PR. This is mostly adding more comments and minor refactoring to make the code even more clear. I am making a major refactoring of the `permutation_2sided` function, based on conversations with @PaulWAyers & @Ali-Tehrani, but I wanted to share this first.
=> Refactor permutation

docs/zreference.bib
This will enable generating a hyperlink to the original website automatically. Fixed the indention with 4 spaces as well.
=> Add DOI for all the references

.readthedocs.yml
This fixes the readthedocs build.
=> Update .readthedocs.yml: docs --> doc

procrustes/generalized.py, procrustes/generic.py, procrustes/kopt.py, procrustes/orthogonal.py, procrustes/permutation.py, procrustes/softassign.py, procrustes/utils.py
Mostly cosmetic changes except for the https://github.com/theochem/procrustes/commit/c3ad6f6f1edb3ad97f08d869778649170dd9d599
There were arguments that are said to be keyword arguments but no default values are provided. I'm not sure if the arguments need to be changed to keyword arguments with the correct value or if the docstring simply needs to be updated. I've assumed the latter.
=> Fix up docstring

README.md, procrustes/generalized.py, procrustes/generic.py, procrustes/kopt.py, procrustes/orthogonal.py, procrustes/permutation.py, procrustes/rotational.py, procrustes/softassign.py, procrustes/symmetric.py, procrustes/utils.py, setup.py
Cosmetic/documentation changes, including:
- Add type hints
- Order imports
- Small docstring fixes
- Add tutorials note to README
- Update README with quickstart, install-from-source and note on running tests
- Load install_requires dynamically from requirements.txt
=> Type hinting, README updates, dynamic install_requires

HEADER, doc/conf.py, procrustes/__init__.py, procrustes/generalized.py, procrustes/generic.py, procrustes/kopt.py, procrustes/orthogonal.py, procrustes/permutation.py, procrustes/rotational.py, procrustes/softassign.py, procrustes/symmetric.py, procrustes/test/__init__.py, procrustes/test/common.py, procrustes/test/test_generalized.py, procrustes/test/test_generic.py, procrustes/test/test_kopt.py, procrustes/test/test_orthogonal.py, procrustes/test/test_permutation.py, procrustes/test/test_rotational.py, procrustes/test/test_softassign.py, procrustes/test/test_symmetric.py, procrustes/test/test_utils.py, procrustes/utils.py, setup.py, updateheaders.py
This PR updates time information in the header sections.
=> Update time stamp: 2021 --> 2022

README.md
Fix typo introduced in the title.
=> Fix typo introduced in the title

.github/workflows/ci_rob.yml, README.md
=> Undo changes to ci_rob.yml

doc/usr_doc_installization.rst
Update `conda install` command line as the old one is outdated.
=> Update `conda install` command line

README.md, procrustes/generalized.py, procrustes/generic.py, procrustes/rotational.py, procrustes/symmetric.py
Also updated README.md by adding code quality badge.
=> Add "__all__" for different modules

.codecov.yml, .github/workflows/ci_codecov.yml
This help with the visualization of code coverage.
=> Add `CodeCov` in CI

procrustes/psdp.py, procrustes/test/test_psdp.py
@FanwangM  @PaulWAyers This is the interim implementation of OptPSDP (the required third algorithm). Tests have passed on my local machine.
The algorithm appears to provide us with better error thresholds when compared to the previous algorithms. However, the threshold is quite nominal for the examples we have had in place. Optimizing the algorithm for the case when $A$ is a diagonal matrix remains.
Thanks to @abhishekmittal15 for helping me understand the MATLAB implementation provided [here](https://in.mathworks.com/matlabcentral/fileexchange/64597-spectral-projected-gradient-method-for-the-positive-semi-definite-procrustes-problem)!
=> OptPSDP (Spectral Gradient Projection Method for PSDP)

README.md
Fix missing `codecov` status icon.
=> Fix missing `codecov` status icon

HEADER, procrustes/__init__.py, procrustes/generalized.py, procrustes/generic.py, procrustes/kopt.py, procrustes/orthogonal.py, procrustes/permutation.py, procrustes/psdp.py, procrustes/rotational.py, procrustes/softassign.py, procrustes/symmetric.py, procrustes/test/__init__.py, procrustes/test/common.py, procrustes/test/test_generalized.py, procrustes/test/test_generic.py, procrustes/test/test_kopt.py, procrustes/test/test_orthogonal.py, procrustes/test/test_permutation.py, procrustes/test/test_psdp.py, procrustes/test/test_rotational.py, procrustes/test/test_softassign.py, procrustes/test/test_symmetric.py, procrustes/test/test_utils.py, procrustes/utils.py, updateheaders.py
Update the LICENSE time stamp.
=> Update time stamp of headers

procrustes/permutation.py
=> Fix incorrect default parameters for `permutation_2sided`

.github/workflows/ci_codecov.yml
This PR updates the Python version.
=> Update Python version for CodeCov

HEADER, doc/conf.py, procrustes/__init__.py, procrustes/generalized.py, procrustes/generic.py, procrustes/kopt.py, procrustes/orthogonal.py, procrustes/permutation.py, procrustes/psdp.py, procrustes/rotational.py, procrustes/softassign.py, procrustes/symmetric.py, procrustes/test/__init__.py, procrustes/test/common.py, procrustes/test/test_generalized.py, procrustes/test/test_generic.py, procrustes/test/test_kopt.py, procrustes/test/test_orthogonal.py, procrustes/test/test_permutation.py, procrustes/test/test_psdp.py, procrustes/test/test_rotational.py, procrustes/test/test_softassign.py, procrustes/test/test_symmetric.py, procrustes/test/test_utils.py, procrustes/utils.py, updateheaders.py
This PR updates the timestamp.
=> Update time stamp to 2025
