theochem/procrustes

- docs/examples/atom_mapping/atom_mapping.py
- procrustes/orthogonal.py
- procrustes/permutation.py
- procrustes/rotational.py
- procrustes/softassign.py
- procrustes/symmetric.py
- procrustes/test/test_utils.py
- procrustes/utils.py
This pull request is only concerned with utils.py and test_utils.py.
Removed
-------------
The following functions and their tests were removed since they weren't used anywhere.
- is_diagonalizable (25824ae) 
- optimal_heuristic (16b0539) 
- check_rank. (6b7f1d0)
The following were removed, since they were one-liners/wrappers over the numpy counterpart.
- eigendecomposition (8e5c058 , b6021fa )
- singular_value_decomposition (6011c6f , 2b76734 )
Other
--------
Fixed documentation for the padding argument. (23b25b4  )
Changed functions that weren't used outside of utils.py to private. (54ffd44)
Added documentation to setup_input_arrays, since it is used in all Procruste's methods (5b874c7 ).
Fixed bug in _zero_padding, where rectangular matrices of the same shape aren't converted to square …
> Refactor utils

- procrustes/orthogonal.py
- procrustes/test/test_orthogonal.py
- procrustes/test/test_permutation.py
This PR fixes the warnings raised by linters: `Possible unbalanced tuple unpacking with sequence defined at line...`. This is probably a short-term fix as it might be better to return a dictionary/class object for various Procrustes functions like `scipy.optimize` returned value.
> Fix linter w0632

- procrustes/generic.py
- procrustes/test/test_generic.py
- procrustes/test/test_orthogonal.py
This generic Procrustes solves the problem of least squares and the solution is given by [Gower, J. C. Procrustes Methods. Wiley Interdisciplinary Reviews: Computational Statistics, 2(4), 503-508, 2010. ](https://onlinelibrary.wiley.com/doi/abs/10.1002/wics.107).  This implementation solves the problem of minimization of AX-B where A and B are the matrices of interest and X is the transformation matrix. 
I put this as a separate module as this generic one is unconstrained optimization and all other one sides Procrustes methods are just conditional optimization under special constraints, such as orthogonal, symmetric, et al.
> Add generic Procrustes for least square problems

- procrustes/generalized.py
- procrustes/test/test_generalized.py
Generalized Procrustes analysis (GPA) seeks an optimal orthogonal transformation for a group of a matrix to fit into one configuration. Important papers on GPA include [Stegmann, Mikkel B., and David Delgado Gomez. "A brief introduction to statistical shape analysis." Informatics and mathematical modelling, Technical University of Denmark, DTU 15, NO. 11 (2002).](https://graphics.stanford.edu/courses/cs164-09-spring/Handouts/paper_shape_spaces_imm403.pdf) and [Gower, John C. "Generalized procrustes analysis." Psychometrika 40, NO. 1 (1975): 33-51.](https://link.springer.com/article/10.1007/BF02291478).
Here we implement the basic algorithm, an alternating least square one, as decrribed in [Gower, John C. "Procrustes methods." Wiley Interdisciplinary Reviews: Computational Statistics 2, …
> Add generalized Procrustes analysis

- procrustes/orthogonal.py
- procrustes/test/test_orthogonal.py
This pull request is regarding refactoring orthogonal.py, in particular the two-side orthogonal Procrustes problem.
Most of these commits were due to my mistakes in rebasing and not being careful, so I apologize.
Two sided orthogonal Procruste problem does not require optimizing the "S" matrix in the documentation/paper.
So the "approximate" and "exact" modes are not needed anymore, (5fc65db,  e4b3f8f ). Consequently, the tests that involve these two modes were removed (e9b9d86, b75ac49). Its errors in the documentation were removed (53f94db ).
I also cleaned it up a bit by removing an else statement, removing some not needed comments.
Since two-sided Procruste problem requires symmetric matrices as input, I added these as tests in three simple cases (179f109 )
> Refactor orthogonal.py

- procrustes/generic.py
- procrustes/orthogonal.py
- procrustes/permutation.py
- procrustes/rotational.py
- procrustes/softassign.py
- procrustes/symmetric.py
- procrustes/test/test_generic.py
- procrustes/test/test_orthogonal.py
- procrustes/test/test_permutation.py
- procrustes/test/test_rotational.py
- procrustes/test/test_softassign.py
- procrustes/test/test_symmetric.py
- procrustes/test/test_utils.py
- procrustes/utils.py
This PR is mainly about to fixe issue #25.
Things addressed in the corresponding codes:
By doing so, we can get rid of potential ambiguity when people read the codes.
> Change ProcrustesResult argument e_opt to error

- procrustes/__init__.py
- procrustes/kopt.py
- procrustes/permutation.py
- procrustes/test/test_kopt.py
- procrustes/test/test_utils.py
- procrustes/utils.py
K-opt heuristic local search algorithms should not belong to the `utils` module and move them to be a separate module is a good choice.
This PR fixed issue, #41
> Isolate k-opt heristic functions as a separate module, Fixes #41

- procrustes/generalized.py
- procrustes/generic.py
- procrustes/orthogonal.py
- procrustes/permutation.py
- procrustes/rotational.py
- procrustes/softassign.py
- procrustes/symmetric.py
- procrustes/test/test_generic.py
- procrustes/test/test_orthogonal.py
- procrustes/test/test_permutation.py
- procrustes/test/test_rotational.py
- procrustes/test/test_softassign.py
- procrustes/test/test_symmetric.py
- procrustes/utils.py
- tox.ini
The `compute_error` and `ProcrustesResult` are refactored.
> Refactor compute_error and ProcrustesResult

- README.md
- docs/notebooks/Atom_Atom_Mapping.ipynb
- docs/notebooks/Chirality_Check.ipynb
- docs/notebooks/Protein_Structure_Alignment.ipynb
- docs/notebooks/Ranking_by_Reordering.ipynb
This PR mainly fixes problems of 
This is an attempt to fix #44.
> Fix Binder and jupyter notebooks

- docs/requirements.txt
This PR is mainly about updating the sphinx static website.
This error is caused by sphinx-bibtex major 2.0.0 release which is incompatible. Using version 1.0.0 can fix this.
For more information, [detailed discussion on `sphinx-bibtex` problem](https://github.com/executablebooks/jupyter-book/issues/1137).
> Fix sphinx building problem

- README.md
This is because we are transferring to GitHub Actions and the outdated Travis CI badge is not working due to a negative credit balance. 
For more information on GitHub Actions badge, please see [blog](https://andresand.medium.com/adding-github-action-workflow-status-badge-to-your-repository-22ccea025af6) and [GitHub docs](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badgebadge_logo).
> Replace Travis CI badge with GitHub Actions one

- README.md
- tox.ini
As Python 3.9 becomes a stable release and Python  3.10 is about to come, we should add support of py39. Both the `tox.ini` and `README.md` are updated.
That's all for this small PR.
> Add testing support for Python 3.9

- procrustes/kopt.py
- procrustes/permutation.py
- procrustes/softassign.py
- procrustes/test/test_kopt.py
This refactors the `kopt` module. I removed the `ref_error` argument because the initial permutation matrix is given, so it can be used to compute the initial error. It is easier to compute it internally than clarify it in the documentation and have the user pre-compute the initial error. Also, the user can erroneously provide an error that does not match the initial permutation matrix. This is how I understand/see things, so please feel free to let me know if anything is missing.
I had a few questions that I will raise in this PR.
> Refactor kopt Module

- procrustes/test/test_rotational.py
This pull requests refactors the tests of rotational.py to include randomized testing.
The matrix size, the padding length, and translation matrix are all random now, whenever they're included.  
Some test function names were changed to be more clear.
One test was removed because it was identical to the previous ones (ec5a321) .
Added a test for raising an error for incorrect inputs, increasing the coverage of this file to 100% (4342296 ).
> Refactor test rotational.py

- procrustes/kopt.py
- procrustes/orthogonal.py
- procrustes/permutation.py
- procrustes/softassign.py
- procrustes/test/test_kopt.py
- procrustes/utils.py
The `compute_error` was computing the norm of `AT-B` when given one matrix (which was fine) but `T.transpose A S - B` when given two matrices (which is not right), because:
1. The T matrix is expected to always be the right-hand-side transformation 
2. The S matrix is the left-hand-side transformation (and is not supposed to be transposed when computing the |SAT-B|)
These inconsistencies are fixed and the code now matches the `compute_error` documentation.
> Make 2-sided Procrustes error match |SAT-B|

- procrustes/orthogonal.py
- procrustes/permutation.py
- procrustes/rotational.py
- procrustes/symmetric.py
This short pull request changes from Numpy SVD function to Scipy SVD function. See issue #69 for more info as to why this choose was made.
These changes were made to orthogonal, permutation, rotational, and symmetric. I was thinking of adding a function variable "lapack_driver" to each of these functions with docstring
`
"lapack_driver : {"gesvd", "gesdd"}, optional
Used in the singular value decomposition function from SciPy. Only allowed two options, with
"gesvd" being less-efficient than "gesdd" but is more robust. Default is "gesvd".
`
Any thoughts @FarnazH
> Change svd

- procrustes/generic.py
- procrustes/symmetric.py
- procrustes/test/common.py
- procrustes/test/test_generic.py
- procrustes/test/test_symmetric.py
This pull request changes how testing is done in symmetric.py to be more general and randomized.
The function signature of Procrustes problem with symmetric matrices is changed wrt to "remove_zero_cols" and "remove_zero_rows" to be more consistent with the other functions with "unpad_col", and "unpad_row" (90ca479).  
Some tests were removed, since they were duplicates with very small matrix size being tested (223c77a).
There were code that was commented out (57ffb8c) and a test (9551c87) corresponding to it that was commented out. I decided to remove them.
> Refactor test symmetric.py

- procrustes/orthogonal.py
- procrustes/test/test_orthogonal.py
This pull request refactors the test in orthogonal.py to make the matrix sizes, orthogonal matrices, translation and padding length to be randomized . It generates a random orthogonal matrix via scipy.stats.ortho_group class.
Some tests were removed because they weren't that much different to the previous tests (a7a1b27,  a7e4e72, f9673c4).
Also added "assert(res.s, None)" and removed the dictionary call of results (5361ceb,  67b15b4).
I removed the term unitary from the function document because all unitary matrices here are orthogonal because singular value decomposition of real-valued matrices contain orthogonal matrices and likewise with eigenvalue decomposition of real, symmetric matrices (7c1dc37).
Added a test for incorrect inputs increasing the code coverage (6c3066a).
I will …
> Refactor test orthogonal

- procrustes/kopt.py
- procrustes/permutation.py
- procrustes/softassign.py
- procrustes/test/test_kopt.py
- tox.ini
The commits are self-explanatory, but to summarize:
The `kopt_heuristic_single` and `kopt_heuristic_double` functions were specifically coded for 2-sided permutation Procrustes with 1- or 2-transformations, respectively, which defeats the purpose of having an independent module (I remember that the goal was being able to apply `kopt` to different problems). Also, the `permutation_2sided_explicit` function had its own kopt-style implementation (going through all permutations), so it was repeated-code and redundant. In this regard:
1. `kopt_heuristic_single` and `kopt_heuristic_double` functions are generalized to take an objective function as an argument
2. There were only two tests for kopt functions, so the tests are extended using random matrices, and two bugs are fixed
3. The …
> Refactor kopt

- procrustes/permutation.py
- procrustes/test/test_permutation.py
- Update the docstring to have the Procrustes formulas at the top
- Change the argument names `remove_zero_col` and `remove_zero_row` to `unpad_col` and `unpad_row`
> Update 1-sided permutation docstring & args name

- procrustes/orthogonal.py
- procrustes/permutation.py
- procrustes/rotational.py
- procrustes/test/test_permutation.py
This pull request is regarding permutation for two-sided, specifically the function permutation_2sided
The variables for unpad_col, unpad_row and pad were updated to match the other functions.
For single transformation, a check was added to make sure that they are square matrices.
Certain part of the code was moved into the if statement.
> Refactor permutation two sided

- conda.recipe/meta.yaml
- setup.py
This PR mainly adds the `meta.yaml` file for `conda` builds and it has passed a test on Fedora 33.
> Add conda build conda recipe, meta.yaml

- procrustes/generic.py
- procrustes/orthogonal.py
- procrustes/permutation.py
- procrustes/rotational.py
- procrustes/symmetric.py
- procrustes/test/test_generic.py
- procrustes/test/test_orthogonal.py
- procrustes/test/test_rotational.py
- procrustes/test/test_symmetric.py
This pull request is about adding the lapack driver option whenever singular value decomposition is used. See issue #78.
I added it to rotational, orthogonal, symmetric, permutation and generic.  I also added tests to these.
The doc string of  "lapack_driver" for permutation and generic are different from the other modules.
For generic, I instead used NumPy's Morse Penrose inverse if "lapack_driver="gessd""  and SciPy's Morse Penrose inverse if "lapack_driver="gesvd"".
> Lapack driver

- procrustes/orthogonal.py
- procrustes/softassign.py
- procrustes/test/test_softassign.py
This pull-request updates the API of the soft-assign.
- Change `remove_zero_row` to `unpad_row` and `remove_zero_col` to `unpad_col`.
- One of the raise errors in othogonal.py was using `remove_zero_row` in its error message.
- Changed `array_a` to `a` and similarly for b matrix, made it more specific that a, b are (N,N) matrices.
- Raise error if shapes of a, b aren't square after padding/removing zero cols/rows. 
- Raise error if shapes of a and b are not the same.
- Added tests for these new raise error statements
- Change the order of function parameters to be the generic first (a, b, pad, unpad_row) then algorithm specifics.
- Changed a previous test to increase coverage to 100.
> Softassign api

- doc/conf.py
- doc/index.rst
- doc/notebooks/Chemical_Structure_Alignment.ipynb
- doc/usr_doc_installization.rst
Following changes are made:
- minor grammar/capitalization/spacing changes
-  Add QCDecs' code of conduct
- Specify Frobenius norm in one of the equation (for consistency)
- Fix nbsphinx behaviour
It'd be great if someone can double-check that the equation for the norm is supposed to be Frobenius (I thought it'd make it consistent with the equation above)
As for nbsphinx, the issue was that the `Quick Start` section was not behaving well (is unavailable in the side panel and is displayed in raw form). I think it depends on which version readthedocs has on their server. I'm pretty sure it's the latest one, but it should be checked once it gets uploaded.
> Fix up documenation

- doc/notebooks/Chemical_Structure_Alignment.ipynb
The original notebook has a problem of accessing the dependencies in the Binder server. Now it's fixed.
> Fix missing dependencies for protein alignment

- README.md
Now we use https://procrustes.qcdevs.org/ to host the documentation.
> Update documentation website url

- README.md
- requirements.txt
This problem is detailed in https://github.com/theochem/procrustes/security/dependabot/1. Now we set `numpy>=1.21.5`
> Fix buffer overflow vulnerability in NumPy 1.9.x

- doc/notebooks/Chemical_Structure_Alignment.ipynb
- doc/notebooks/Chirality_Check.ipynb
The original block downloads the input files with the same directory
of the Jupyter files, but this is redundant if one clones the repo.
Moreover, if one runs the Procrustes analysis blocks without running
the download block, it will result to errors as the file path it points
to is not right. Now everything is fixed and running in Binder does not
require people to download the input files.
> Fix input file download and `nbsphinx` rendering

- CITATION.cff
- README.md
- doc/index.rst
The `CITATION.cff` was generated based on https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files.
> Add `CITATION.cff` to enable automatic citation style generation

- procrustes/generic.py
- procrustes/test/test_generic.py
More details is listed in https://github.com/scipy/scipy/issues/8861#issuecomment-1030803006
This PR fixes #174.
> Remove deprecated `pinv2` function in `scipy`

- procrustes/psdp.py
- procrustes/test/test_psdp.py
The first commit deals with #172. Scaling, translation etc. have been fixed for the input arrays. There are some changes to docstring too. Namely:
- Representing $R$ as $\mathbb{R}$.
- Using citations and references better within the docstring.
- Clarifying why $\mathbf{A}$ and $\mathbf{B}$ are referred to as $\mathbf{G}$ and $\mathbf{F}$ respectively.
> Testing for PSDP

- README.md
- codecov.yml
This PR fixes the original incorrect coverage report by excluding some PY files that are not algorithm implementation. Fix the file name of codecov configuration where the file with dot cannot be recognized by the web server.
> Add `codecov` coverage badge

- doc/notebooks/Quick_Start.ipynb
- requirements.txt
- setup.py
- tox.ini
This PR fixes the question mentioned in https://github.com/theochem/procrustes/issues/166 , which showed examples on how to access the scaling factor and translation matrix.
> Add information about translation and scaling

- procrustes/psdp.py
- procrustes/test/test_psdp.py
This stands in place of #180 in order to keep the git log clean as @FanwangM mentioned.
> Peng's Algorithm (updated PR)

- doc/notebooks/Quick_Start.ipynb
Adjusted wording and fixed a couple typos related to the translation/scaling clarification made by @FanwangM . 
With these pull requests, it should be easy for a user to print out translation/scaling factors as needed, as well as recover the translated/scaled versions of the array $a$.
> Clarify quickstart notebook re translation/scaling

- .github/workflows/ci_tox.yml
- procrustes/psdp.py
- procrustes/test/test_psdp.py
- tox.ini
Hi @FanwangM , I have implemented the 1st algorithm mentioned in #194 , the Projected Gradient method and written the tests for it by taking the input matrices from the woodgate algorithm tests and the error percentages are better in certain cases. I will fix the docstrings soon and start implementing the Fast Gradient method. Looking forward to your feedback on the current code. Also I had a question regarding the file `psdp.py`, is it advisable to add all the algorithms to the same file, as the file is already getting really large, maybe we can shift some helper functions somewhere else and probably create a folder for PSDP and put each algorithm into its own file? What do you suggest we do?
> PSDP Algorithms

- procrustes/generic.py
This is fixed by adding a small random noise, as discussed in https://github.com/theochem/procrustes/issues/197. 
The `pinv` function is implemented in
https://github.com/scipy/scipy/blob/4bd5e943cbf30efde4becea48c388faafa14e9e4/scipy/linalg/_basic.py#L1447, which replies on https://github.com/scipy/scipy/blob/4bd5e943cbf30efde4becea48c388faafa14e9e4/scipy/linalg/_decomp_svd.py#L13-L169. The implementation of `pinv` only checks explicitly if the tolerance values are valid.
> Add case when matrix is ill-conditioned for generic procrustes

- .github/workflows/ci_codecov.yml
- pyproject.toml
- tox.ini
> Add too-many-positional-arguments to ignore list for `pylint`
